Fully localized. Added interface language in settings
Bible-Translation-Tools/BTT-Writer-Desktop pull request #173
Opened 2024-01-03 14:08 UTC by mXaln

2024-01-18 20:09 UTC, PurpleGuitar requested changes
Max, the localization changes look great.  It looks like maybe some of the dark mode changes got reverted, which I left comments on.  Could you double-check those sections and see if we need to put those changes back?

2024-01-19 11:11 UTC, mXaln commented on src/elements/ts-home/ts-home-sidebar.html
> +            color: white;
Actually, here the color rule is redundant, because we don't have any text in the sidebar. So I removed it.

2024-01-19 11:11 UTC, mXaln commented on src/elements/ts-main/ts-app-titlebar.html
> +            color: white;
Removed as redundant rule

2024-01-19 11:12 UTC, mXaln commented on src/elements/ts-main/ts-dashboard.html
> +          color: white;
Here, because status bar background is blueish in both themes, the color should be always white.

2024-01-19 11:13 UTC, mXaln commented on src/elements/ts-profile/ts-profile-sidebar.html
> +            color: white;
Removed as redundant rule.

2024-01-19 11:14 UTC, mXaln commented on src/elements/ts-profile/ts-profile.html
> +            color: white;
Same as with status bar. #heading background is blueish in both themes, thus the color should be always white.

2024-02-07 20:25 UTC, PurpleGuitar approved these changes

2024-02-07 20:27 UTC, merged