Dark theme
Bible-Translation-Tools/BTT-Writer-Desktop pull request #88
Opened 2022-09-27 10:58 UTC by mXaln

Fixes # .

Changes in this pull request:
-
-
-

2022-09-29 20:22 UTC, PurpleGuitar requested changes
Max, these changes look good, but let's get some feedback from Dan about the secrets failure on build before we merge it in.

2022-10-07 10:10 UTC, mXaln commented
> Max, these changes look good, but let's get some feedback from Dan about the secrets failure on build before we merge it in.

Done.

2022-10-26 15:23 UTC, OpThomasPrime1 commented
Verified by QA on Windows 10, 11, Mac, and Linux

2022-11-17 21:59 UTC, PurpleGuitar approved these changes

2022-11-17 21:59 UTC, merged